export default {
  MIN_CHARS_TO_FETCH_RESULTS: 2,
  MAX_AUTO_COMPLETE_RESULTS: 15,
  DISPLAY_DATE_FORMAT: "DD-MM-YYYY",
  MAX_CHECKIN_DATE_ALLOWED_PERIOD: 365, // days
  MAX_CHECKOUT_DATE_ALLOWED_PERIOD: 28, // days
  MAX_ROOMS_COUNT: 4,
  MIN_ROOMS_COUNT: 1,
  MAX_GUESTS_COUNT_PER_ROOM: 4,
  MAX_ADULTS_COUNT_PER_ROOM: 4,
  MIN_ADULTS_COUNT_PER_ROOM: 1,
  MAX_CHILDREN_COUNT_PER_ROOM: 2,
  MIN_CHILDREN_COUNT_PER_ROOM: 0
};
