export default {
  MIN_CHARS_TO_AUTOCOMPLETE_RESULTS: 1,
  MAX_AUTO_COMPLETE_RESULTS: 15,
  DEBOUNCE_TIME: 300,
  HIGHLIGHT_MATCHED_WORDS: true,
  DEFAULT_PLACEHOLDER: '',
  DEFAULT_TEST_KEY: '',
  EMPTY_RESULTS_ON_EMPTY_QUERY: true,
  HIGHLIGHT_RESULTS: true,
};
