export default {
  MIN_CHARS_TO_AUTOCOMPLETE_RESULTS: 1,
  MAX_AUTO_COMPLETE_RESULTS: 15,
  DEBOUNCE_TIME: 300,
  HIGHLIGHT_MATCHED_WORDS: true,
  DEFAULT_PLACEHOLDER: '',
  DEFAULT_TEST_KEY: '',
  EMPTY_RESULTS_ON_EMPTY_QUERY: true,
  HIGHLIGHT_RESULTS: true,
  NO_RESULTS_MESSAGE: 'No results found',
  SHOW_NO_RESULTS_MESSAGE: true,
  SEARCH_KEY: 'title',
  USE_CATEGORIES: false,
};
